---

name: Ruby | publish gem

on:
  push:
    branches:
      - task/tec-79/dockerize # FIXME - only for testing
    tags:
      - "v*"

jobs:
  publish_gem:
    name: publish_gem
    runs-on: ubuntu-latest

    steps:
      - name: do checkout
        uses: actions/checkout@master

      - name: set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: manage token(s) for package registry(s)
        run: |
          mkdir -p $HOME/.gem
          # GPR
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" >> $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.RACECAR_GEM_PUBLISH_TOKEN}}"

      - name: build gem(s)
        run: gem build *.gemspec

      - name: publish
        run: >-
          gem push
          --KEY github
          --host https://rubygems.pkg.github.com/${OWNER}
          *.gem
        env:
          OWNER: ${{ github.repository_owner }}

...
